default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: kadai-tasklist_development

production:
  <<: *default
  database: kadai-tasklist_production
  username: kadai-tasklist
  password: <%= ENV['KADAI-TASKLIST_DATABASE_PASSWORD'] %>
